### ISSUE TITLE
Teste 2

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#10]
```yaml
start_date: 2023/05/19 14:00:00
due_date: 2023/05/19 17:00:00
progress: 0
parent: 
```
