### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#11]
```yaml
start_date: 2023/05/19 18:00:00
due_date: 2023/05/19 21:00:00
progress: 0
parent: 
```
