### ISSUE TITLE
Teste 2

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#12]
```yaml
start_date: 2023/06/04 12:00:00
due_date: 2023/06/04 14:00:00
progress: 0
parent: 
```
