### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#3]
```yaml
start_date: 2023/02/08 16:47:48
due_date: 2023/02/08 16:47:48
progress: 0
parent: 
```

Teste
