### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#4]
```yaml
start_date: 2023/02/08 15:00:00
due_date: 2023/02/08 18:00:00
progress: 0
parent: 
```

Teste
