### ISSUE TITLE
Teste 2

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#5]
```yaml
start_date: 2023/02/13 21:00:00
due_date: 2023/02/14 00:00:00
progress: 0
parent: 
```
