### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/wladrbarbosa#9]
```yaml
start_date: 2023/05/19 12:00:00
due_date: 2023/05/19 15:00:00
progress: 0
parent: 
```
